
spring:
  application:
    name: department-service
  config:
    import: "optional:configserver:http://localhost:8088"
    # this has added because of config server, now also add dependency in pom.xml file


